services:
  - type: web
    name: expense-tracker-backend
    env: docker
    plan: free
    dockerfilePath: server/Dockerfile
    envVars:
      - key: PORT
        value: 3000

  - type: web
    name: expense-tracker-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://expense-tracker-backend-wjpk.onrender.com
